language: clojure
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw | sh
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install emacs-24.5-bin --skip --use
  - cask
lein: lein2
env:
 - PROFILE=default
 - PROFILE=3.5.0
 - PROFILE=3.4.10
 - PROFILE=3.4.9
 - PROFILE=3.4.8
 - PROFILE=1.7
 - PROFILE=1.8
 - PROFILE=1.8-direct
script:
 - lein2 with-profiles $PROFILE test
 - make html
jdk:
 - openjdk7
 - oraclejdk8
notifications:
   email:
     - travis@russet.org.uk
